name: Run C++ Files Sequentially

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cpp-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up C++ build environment
        run: sudo apt-get install g++
        
      - name: Compile and run projectpart2.cpp
        run: |
          g++ -fopenmp projectpart2.cpp -o projectpart2
          ./projectpart2

      - name: Compile and run testpart2.cpp
        run: |
          g++ -fopenmp testpart2.cpp -o testpart2
          ./testpart2

      - name: Compile and run projectpart1.cpp
        run: |
          g++ projectpart1.cpp -o projectpart1
          ./projectpart1

      - name: Compile and run test1234.cpp
        run: |
          g++ test1234.cpp -o test1234
          ./test1234
