name: Run C++ Files Sequentially

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cpp-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up C++ build environment
        run: sudo apt-get install g++

      - name: Compile and run projectpart2.cpp
        run: |
          g++ projectpart2.cpp -o projectpart2
          ./projectpart2

      - name: Compile and run testpart2.cpp
        run: |
          g++ testpart2.cpp -o testpart2
          ./testpart2